apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: backend
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: backend
     template:
       metadata:
         labels:
           app: backend
       spec:
         containers:
           - name: backend
             image: backend:latest
             ports:
               - containerPort: 3001
             env:
               - name: DATABASE_URL
                 value: postgres://user:password@postgres:5432/tododb
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: backend
   spec:
     ports:
       - port: 3001
         targetPort: 3001
     selector:
       app: backend
