name: CI/CD Pipeline
   on:
     push:
       branches:
         - main
   jobs:
     lint-and-test:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - name: Set up Node.js
           uses: actions/setup-node@v3
           with:
             node-version: '18'
         - name: Lint Backend
           run: |
             cd backend
             npm install
             npm run lint
         - name: Test Backend
           run: |
             cd backend
             npm test
         - name: Lint Frontend
           run: |
             cd frontend
             npm install
             npm run lint
     deploy:
       runs-on: ubuntu-latest
       needs: lint-and-test
       steps:
         - uses: actions/checkout@v3
         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v2
         - name: Build and push backend
           run: |
             docker build -t backend:latest ./backend
             docker save backend:latest | gzip > backend.tar.gz
         - name: Build and push frontend
           run: |
             docker build -t frontend:latest ./frontend
             docker save frontend:latest | gzip > frontend.tar.gz
         - name: Deploy to Minikube
           run: |
             minikube start
             minikube image load backend:latest
             minikube image load frontend:latest
             kubectl apply -f kubernetes/postgres-deployment.yaml
             kubectl apply -f kubernetes/backend-deployment.yaml
             kubectl apply -f kubernetes/frontend-deployment.yaml
